# Generated by Django 5.0.4 on 2024-07-09 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0007_alter_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=models.TextField(),
        ),
    ]
