# Generated by Django 5.0.4 on 2024-07-09 23:38

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0008_alter_blogs_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='description',
            field=froala_editor.fields.FroalaField(max_length=10000000),
        ),
    ]
