# Generated by Django 5.0.4 on 2024-07-11 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0014_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentaire',
            new_name='comment',
        ),
    ]
