# Generated by Django 5.0.4 on 2024-07-11 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0015_rename_commentaire_comment_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='product',
        ),
    ]
