# Generated by Django 5.0.4 on 2024-07-12 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0020_rename_profil_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
    ]
