# Generated by Django 5.0.4 on 2024-07-16 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0024_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
