# Generated by Django 5.0.4 on 2024-07-16 08:53

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0025_delete_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_body', froala_editor.fields.FroalaField()),
                ('sub_about_body', froala_editor.fields.FroalaField()),
            ],
        ),
    ]
