# Generated by Django 5.0.4 on 2024-07-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0026_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image_about',
            field=models.ImageField(default=1, upload_to='image_about'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about_body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='sub_about_body',
            field=models.TextField(),
        ),
    ]
