# Generated by Django 5.0.4 on 2024-07-16 11:00

import froala_editor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0027_about_image_about_alter_about_about_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='image_about',
            new_name='image1_about',
        ),
        migrations.RemoveField(
            model_name='about',
            name='sub_about_body',
        ),
        migrations.AddField(
            model_name='about',
            name='image2_about',
            field=models.ImageField(default=1, upload_to='image_about'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='about',
            name='about_body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
