# Generated by Django 5.0.4 on 2024-07-16 11:05

import froala_editor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0028_rename_image_about_about_image1_about_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='sub_about_body',
            field=froala_editor.fields.FroalaField(default=1),
            preserve_default=False,
        ),
    ]
