# Generated by Django 5.0.4 on 2024-07-16 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0029_about_sub_about_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='desc',
        ),
    ]
